name: Deploy Feature Candidate

description: Deploy Feature Candidate / FC

inputs:
  DEPLOY_ENV:
    required: true
    description: ENV
  SVC_NAME:
    required: true
    description: Name service
  SSH_PRIV_KEY_LIBRARY:
    required: true
    description: SSH_PRIV_KEY_LIBRARY

runs:
  using: "composite"
  steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Upgrade wheel, setuptools, virtualenv
      run: python2 --version; python2 -m pip install --upgrade pip wheel setuptools virtualenv
      shell: bash
    
    - name: Get SSH_KEY LIBS-BACKEND
      run: echo "${{inputs.SSH_PRIV_KEY_LIBRARY}}" > ssh-rsa.key ; atar-cli deploy --set-ssh=ssh-rsa.key ; rm -f ssh-rsa.key
      shell: bash
    
    - name: Update Client/Update Third Party
      run: atar-cli --update-all
      shell: bash

    - name: Export variables
      run: |
        TAG=$(atar-cli ci -j=${GITHUB_REF_NAME} 2>&1)
        echo "TAG=${TAG}" >> $GITHUB_ENV
      shell: bash

    - name: GCloud Deploy - HML
      run: echo ${ATAR_CREDENTIALS_DEV}|gcloud auth activate-service-account --key-file=-
      shell: bash
    
    - name: Deploy ATAR_DEV ${{github.event.repository.name}} - ${{env.TAG}}
      run: ${RETRY} gcloud -q --project=${ATAR_PROJECT_DEV} app deploy app.yaml -v=${{env.TAG}} --no-promote
      shell: bash