name: Deploy Feature Candidate

description: Deploy Feature Candidate / FC

inputs:
  DEPLOY_ENV:
    required: true
    description: ENV
  SVC_NAME:
    required: true
    description: Name service
  SSH_PRIV_KEY_LIBRARY:
    required: true
    description: SSH_PRIV_KEY_LIBRARY

runs:
  using: "composite"
  steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Export variables
      run: |
        TAG=$(atar-cli ci -j=${GITHUB_REF_NAME} 2>&1)
        echo "TAG=${TAG}" >> $GITHUB_ENV
      shell: bash

    - name: Build FRONTEND STAGING
      run: rm -rf node_modules dist; sudo npm install; npm run build-staging
      shell: bash

    - name: GCloud Auth ATAR
      run: echo ${ATAR_CREDENTIALS_DEV}|gcloud auth activate-service-account --key-file=-
      shell: bash

    - name: STAGING -> Deploy FRONTEND ${{env.repo_name}} - ${{env.app_version}}
      run: |
        cd erp
        ${RETRY} gcloud -q --project=${ATAR_PROJECT_DEV} app deploy app.porto-hml.yaml -v=${{env.TAG}} --no-promote
        ${RETRY} gcloud -q --project=${ATAR_PROJECT_DEV} app deploy app.atar-hml.yaml -v=${{env.TAG}} --no-promote
      shell: bash
