name: Deploy Feature Candidate

description: Deploy Feature Candidate / FC

inputs:
  DEPLOY_ENV:
    required: true
    description: ENV
  GITHUB_TOKEN:
    required: true
    description: token

runs:
  using: "composite"
  steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        ref: "main"

    - name: Check Current Branch
      id: current
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "devops@atarb2b.com"
        echo "CURRENT_DATE=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV
        echo "CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT
        echo "BRANCH="$(echo $CURRENT_BRANCH | cut -c 4-)"" >> $GITHUB_ENV
      shell: bash

    - name: GCloud Deploy
      run: |
        echo ${ATAR_CREDENTIALS_DEV}|gcloud auth activate-service-account --key-file=-
      shell: bash
    
    - name: Deploy ${{github.event.repository.name}}
      run: |
        OLD_TAG=${{env.BRANCH}} 
        TAG="${OLD_TAG//./-}"
        ${RETRY} gcloud -q --project=${ATAR_PROJECT_DEV} app deploy app.${{ inputs.DEPLOY_ENV }}.yaml -v=$TAG --no-promote
      shell: bash

    # - name: Send Message to Slack
    #   uses: 8398a7/action-slack@v3
    #   with:
    #     status: ${{job.status}}
    #     username: "DEPLOY_FC|${{github.event.repository.name}}|${{ inputs.TAG }}"
    #     author_name: ${{github.workflow}}
    #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
    #   if: always()
