name: Deploy Feature Candidate

description: Deploy Feature Candidate / FC

inputs:
  DEPLOY_ENV:
    required: true
    description: ENV
  GITHUB_TOKEN:
    required: true
    description: token

runs:
  using: "composite"
  steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Delete GAE versions
      uses: vijayp23/delete-gae-version-action@1.0.0
      with:
        service-account: ${ATAR_CREDENTIALS_DEV}
        project-id: ${ATAR_PROJECT_DEV}
        service-name: authorizer-teste
        retain-versions: 1
        debug: true

    - name: GCloud Deploy
      run: |
        echo ${ATAR_CREDENTIALS_DEV}|gcloud auth activate-service-account --key-file=-
      shell: bash
    
    - name: Deploy ${{github.event.repository.name}}
      run: |
        BRANCH=$(echo ${GITHUB_REF#refs/heads/fc/})
        echo $BRANCH
        ${RETRY} gcloud -q --project=${ATAR_PROJECT_DEV} app deploy app.${{ inputs.DEPLOY_ENV }}.yaml -v=$BRANCH --no-promote
      shell: bash

    # - name: Send Message to Slack
    #   uses: 8398a7/action-slack@v3
    #   with:
    #     status: ${{job.status}}
    #     username: "DEPLOY_FC|${{github.event.repository.name}}|${{ inputs.TAG }}"
    #     author_name: ${{github.workflow}}
    #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
    #   if: always()
