name: Deploy Feature Candidate

description: Deploy Feature Candidate / FC

inputs:
  DEPLOY_ENV:
    required: true
    description: ENV
  SVC_NAME:
    required: true
    description: Name service
  SSH_PRIV_KEY_LIBRARY:
    required: true
    description: SSH_PRIV_KEY_LIBRARY

runs:
  using: "composite"
  steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Export variables
      run: |
        TAG=$(atar-cli ci -j=${GITHUB_REF_NAME} 2>&1)
        echo "TAG=${TAG}" >> $GITHUB_ENV
      shell: bash

    - name: GCloud Auth ATAR
      run: |
          echo $ATAR_CREDENTIALS|gcloud auth activate-service-account --key-file=-
          echo @atarb2b:registry=https://${ARTIFACT_LOCATION}-npm.pkg.dev/${ATAR_PROJECT}/atar-fe-cli/ > .npmrc
          echo '//${ARTIFACT_LOCATION}-npm.pkg.dev/${ATAR_PROJECT}/atar-fe-cli/:always-auth=true' >> .npmrc
          npx google-artifactregistry-auth --repo-config=.npmrc --credential-config=.npmrc
      shell: bash

    - name: Build FRONTEND STAGING
      run: rm -rf node_modules dist; sudo npm install; npm run build
      shell: bash

    - name: STAGING -> Deploy INTERNET-BANKING ${{env.repo_name}} - ${{env.app_version}}
      run: |
        ${RETRY} gcloud -q --project=${ATAR_PROJECT_DEV} app deploy app.yaml -v=${{env.TAG}} --no-promote --no-cache
      shell: bash
