name: Deploy Feature Candidate

description: Deploy Feature Candidate / FC

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Export variables
      run: |
        TAG=$(atar-cli ci -j=${GITHUB_REF_NAME} 2>&1)
        echo "TAG=${TAG}" >> $GITHUB_ENV
      shell: bash

    - name: GCloud Deploy - HML
      run: echo ${ATAR_CREDENTIALS_DEV}|gcloud auth activate-service-account --key-file=-
      shell: bash
    - name: Deploy ATAR_DEV ${{github.event.repository.name}} - ${{env.TAG}}
      run: ${RETRY} gcloud -q --project=${ATAR_PROJECT_DEV} app deploy app.yaml -v=${{env.TAG}} --no-promote
      shell: bash