name: Deploy Feature Candidate

description: Deploy Feature Candidate / FC

inputs:
  DEPLOY_ENV:
    required: true
    description: ENV
  SVC_NAME:
    required: true
    description: Name service

runs:
  using: "composite"
  steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: GAE Key
      run: |
        echo ${ATAR_CREDENTIALS_DEV}|gcloud auth activate-service-account --key-file=-
      shell: bash
    
    - name: GAE Deploy ${{github.event.repository.name}}
      run: |
        BRANCH=$(echo ${GITHUB_REF#refs/heads/fc/})
        ${RETRY} gcloud -q --project=${ATAR_PROJECT_DEV} app deploy app.${{ inputs.DEPLOY_ENV }}.yaml -v=$BRANCH --no-promote
      shell: bash

    # - name: GAE Version
    #   run: |
    #     gcloud app versions list --project=${ATAR_PROJECT_DEV} --service ${{ inputs.SVC_NAME }} --format="value(version.id)" --sort-by="~version.createTime" | tail -n +2 | xargs -r gcloud app versions delete --project=${ATAR_PROJECT_DEV} --quiet
    #   shell: bash