name: Deploy Feature Candidate

description: Deploy Feature Candidate / FC

inputs:
  ATAR_PROJECT:
    required: true
    description: ""
  ATAR_CREDENTIALS:
    required: true
    description: ""

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Export variables
      run: |
        TAG=$(atar-cli ci -j=${GITHUB_REF_NAME} 2>&1)
        RETRY: "retry -l -i=60s -c=3" >> $GITHUB_ENV
        echo "TAG=${TAG}" >> $GITHUB_ENV
      shell: bash

    - name: GCloud Deploy - HML
      run: echo ${{ inputs.ATAR_CREDENTIALS }} | gcloud auth activate-service-account --key-file=-
      shell: bash
    - name: Deploy ATAR_DEV ${{github.event.repository.name}} - ${{env.TAG}}
      run: ${RETRY} gcloud -q --project=${{ inputs.ATAR_PROJECT }} app deploy app.yaml -v=${{env.TAG}} --no-promote
      shell: bash