name: Deploy Feature Candidate

description: Deploy Feature Candidate / FC

inputs:
  ENV_DEPLOY:
    required: true
    description: ENV
  VERSION:
    required: true
    description: VERSION
  TAG:
    required: true
    description: TAG
  GITHUB_TOKEN:
    required: true
    description: token
  ATAR_PROJECT_DEV:
    required: true
    description: ATAR_PROJECT_DEV
  ATAR_CREDENTIALS_DEV:
    required: true
    description: ATAR_CREDENTIALS_DEV
  SLACK_WEBHOOK_URL:
    required: true
    description: SLACK_WEBHOOK_URL
  RETRY:
    required: true
    description: RETRY

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy AppEngine ${{github.event.repository.name}} - ${{env.TAG}}
      run: |
        echo $ATAR_CREDENTIALS_DEV|gcloud auth activate-service-account --key-file=-
        ${RETRY} gcloud -q --project=${{ inputs.ATAR_PROJECT_DEV }} app deploy app.${{ inputs.ENV_DEPLOY }}.yaml -v=${{env.TAG}} --promote
      shell: bash

    - name: Send Message to Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{job.status}}
        username: "DEPLOY_FC|${{github.event.repository.name}}|${{ inputs.TAG }}"
        author_name: ${{github.workflow}}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
      if: always()
